[config.wallpaper]
set = true
command = "swww"
arguments = ["img", "--transition-type", "center"]
post_hook = '''
for output in $(swww query | grep Output | awk "{print \$2}"); do
  swww img {{ image_path }} --outputs $output --transition-type center
done
'''


[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar; waybar & disown'

