#!/usr/bin/env bash
BATTERY_STATUS=$(cat /sys/class/power_supply/BAT0/status)
BATTERY_PERC=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ "$BATTERY_STATUS" == "Charging" ]]; then
notify-send -u normal -t 2000 -w "Charging"	
paplay /usr/share/sounds/freedesktop/stereo/power-plug.oga
fi

if [[ "${BATTERY_PERC}" -eq 100 ]] && [[ "${BATTERY_STATUS}" == "Full" ]]; then
	notify-send -u normal -t 2000 -w "Fully Charged"
fi

if [[ "${BATTERY_STATUS}" == "Discharging" ]] && [[ "${BATTERY_PERC}" -eq 19 ]]; then
	notify-send -u critical "lilbro you down as hell"
	paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga
fi
